Update list of supported python versions (#22)
* Update list of supported python versions

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

* isAlive() -> is_alive()

https://github.com/python/cpython/pull/15225/files

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

* nose breaks with python-3.10-dev

```
  File "/home/travis/virtualenv/python3.10-dev/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
```

https://travis-ci.org/github/pinterest/thrift-tools/jobs/768931079

One possible solution is to move to nose2.

Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>